add styles
SerhiiOnyshchenko/team-project pull request #18
Opened 2022-01-15 19:54 UTC by OlhaYakubovych

2022-01-15 21:21 UTC, SerhiiOnyshchenko requested changes

2022-01-15 21:21 UTC, SerhiiOnyshchenko commented on src/partials/contacts.html
> +                <p class="contacts__pre-title">FOODTRUCK</p>
food truck це два слова

2022-01-15 21:21 UTC, SerhiiOnyshchenko commented on src/sass/_contacts.scss
> +  padding-left: 20px;
padding-right потрібно теж добавити.
краще те що закоментовано в 36 строці розкоментуй.

2022-01-15 21:21 UTC, SerhiiOnyshchenko commented on src/sass/_contacts.scss
> +  height: 16px;
висоту і ширину видали, а замість них задай радінги 15 з ліва і права та 5 з верху і низу
також допиши text-transform: uppercase;

2022-01-15 21:21 UTC, SerhiiOnyshchenko commented on src/sass/_contacts.scss
> +  //font-size: 12px;
це розкоментуй

2022-01-15 21:21 UTC, SerhiiOnyshchenko commented on src/sass/_contacts.scss
> +  margin-top: 25px;
цей марджен задай в .contacts__pre-title але як марджен-ботом

2022-01-15 21:21 UTC, SerhiiOnyshchenko commented on src/sass/_contacts.scss
> +  margin-top: 25px;
цей марджен задай в .contacts__after-title але як марджен-ботом

2022-01-15 21:21 UTC, SerhiiOnyshchenko commented on src/sass/_contacts.scss
> +  margin-bottom: 113px;
це видали, а для відступу в низ задай радінг-ботом в класі .contacts

2022-01-15 21:21 UTC, SerhiiOnyshchenko commented on src/sass/_contacts.scss
> +  margin-top: 54px;
цей марджен задай в .contacts__list але як марджен-ботом

2022-01-16 08:53 UTC, OlhaYakubovych commented on src/sass/_contacts.scss
> +  height: 16px;
По данному моменту я еще поработаю...

2022-01-16 08:59 UTC, SerhiiOnyshchenko approved these changes

2022-01-16 09:02 UTC, SerhiiOnyshchenko commented
все ок, приймаю

2022-01-16 09:02 UTC, merged