Slider
SerhiiOnyshchenko/team-project pull request #41
Opened 2022-01-17 21:29 UTC by IvannaGumeniuk

2022-01-17 22:50 UTC, SerhiiOnyshchenko requested changes
104 строка в scss margin-bottom: 30px; поміняй на 45рх
107 строка margin-bottom: 35px; поміняй на 50рх

2022-01-17 22:50 UTC, SerhiiOnyshchenko commented on src/sass/_customer.scss
> +    bottom: -30px;
тут задай 10рх без мінуса

2022-01-17 22:50 UTC, SerhiiOnyshchenko commented on src/sass/_customer.scss
> +
а з 53 по 61 видали

2022-01-18 08:14 UTC, IvannaGumeniuk commented on src/sass/_customer.scss
> +
коли я видаляю ці параметри, то псевдоелемент "червоні точки" стоють на сірому фоні, а вони мають бути під ним

2022-01-18 08:16 UTC, IvannaGumeniuk commented on src/sass/_customer.scss
> +    bottom: -30px;
коли я змінюю на 10, то псевдоелемент "червоні точки" на моб версії стоють на сірому фоні, а вони мають бути під ним

2022-01-18 08:19 UTC, SerhiiOnyshchenko commented on src/sass/_customer.scss
> +    bottom: -30px;
стоп я помилився, чомусь подумав що че відступ для пагінації

2022-01-18 08:21 UTC, SerhiiOnyshchenko commented
добре роби коміт а там вже подивлюся як пагінацію здвинути чуть нижче

2022-01-18 08:27 UTC, SerhiiOnyshchenko commented
знайшо як це зробити допиши в кінці ось це:

.swiper-horizontal > .swiper-pagination-bullets,
.swiper-pagination-bullets.swiper-pagination-horizontal,
.swiper-pagination-custom,
.swiper-pagination-fraction {
	bottom: 0;
}

2022-01-18 08:30 UTC, SerhiiOnyshchenko approved these changes

2022-01-18 08:30 UTC, merged