Origin/about
SerhiiOnyshchenko/team-project pull request #5
Opened 2022-01-14 21:07 UTC by Y0ko

Чи правильно зпозиціоновані картинки молока.

2022-01-14 21:17 UTC, Y0ko commented
І чи є правильною дією, огорнути в діви фрагменти, щоб потом зробити дісплей флекс, щоб в планшеті зробити сітку з картинки і текстових блоків?

2022-01-14 21:35 UTC, SerhiiOnyshchenko requested changes
також видали картинки:
about-bucket-apple.png
about-bucket-milk.png
about-ice.png

2022-01-14 21:35 UTC, SerhiiOnyshchenko commented on src/partials/about.html
> +            media="(min-width: 320px)"
min-width:480px

2022-01-14 21:35 UTC, SerhiiOnyshchenko commented on src/partials/about.html
> +
із 28 строчки по 41 видали. ці картинко потрібно вставляти на задній фон через backgraund.

2022-01-14 21:35 UTC, SerhiiOnyshchenko commented on src/partials/about.html
> +        /> -->
із 49 по 53 видали. це зайве

2022-01-14 21:35 UTC, SerhiiOnyshchenko commented on src/partials/about.html
> +          <span class="about-btn-text">Read more</span>
тег span тут не потрібен, текст можеш відстилізувати через саму кнопку, задавши їй стилі.

2022-01-14 21:35 UTC, SerhiiOnyshchenko commented on src/sass/_about.scss
> +  padding-bottom: 15px;
відступ в низ задається мардженом

2022-01-14 21:35 UTC, SerhiiOnyshchenko commented on src/sass/_about.scss
> +  padding-top: 125px;
а це тут не повинно бути. щоб зробити відступ з верху задай цей падінг класу section

2022-01-14 21:35 UTC, SerhiiOnyshchenko commented on src/sass/_about.scss
> +  padding-bottom: 26px;
аналогічно марджен низ

2022-01-14 21:35 UTC, SerhiiOnyshchenko commented on src/sass/_about.scss
> +  font-family: DM Sans;
ця строка зайва, видали

2022-01-14 21:35 UTC, SerhiiOnyshchenko commented on src/sass/_about.scss
> +}
із 66 по 98 строку код не потрібен

2022-01-14 21:35 UTC, SerhiiOnyshchenko commented on src/sass/_about.scss
> +  font-family: DM Sans;
ця строка зайва, видали

2022-01-14 21:35 UTC, SerhiiOnyshchenko commented on src/sass/_about.scss
> +  font-weight: normal;
ця строка зайва, видали

2022-01-14 21:35 UTC, SerhiiOnyshchenko commented on src/sass/_about.scss
> +  font-family: DM Sans;
ця строка зайва, видали

2022-01-14 21:35 UTC, SerhiiOnyshchenko commented on src/sass/_about.scss
> +  font-family: DM Sans;
ця строка зайва, видали

2022-01-14 21:35 UTC, SerhiiOnyshchenko commented on src/sass/_about.scss
> +  font-size: 14px;
ця строка зайва, видали

2022-01-14 21:35 UTC, SerhiiOnyshchenko commented on src/sass/_about.scss
> +  font-size: 14px;
ця строка зайва, видали

2022-01-15 14:48 UTC, SerhiiOnyshchenko approved these changes

2022-01-15 14:48 UTC, merged

2022-01-15 14:50 UTC, SerhiiOnyshchenko reviewed
все ок